<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ruchi-VPCEG35EN" name="Test" tests="2" failures="2" timestamp="13 Jun 2016 13:57:41 GMT" time="0.098" errors="0">
  <testcase name="@AfterClass afterClass" time="0.0" classname="com.pack.tests.helloTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.pack.common.SeleniumLibs.stopSelenium(Unknown Source)
	at com.pack.tests.helloTest.afterClass(helloTest.java:55)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="test11" time="0.016" classname="com.pack.tests.helloTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.text.MessageFormat.applyPattern(MessageFormat.java:436)
	at java.text.MessageFormat.<init>(MessageFormat.java:363)
	at java.text.MessageFormat.format(MessageFormat.java:835)
	at com.pack.common.QLogger.log(Unknown Source)
	at com.pack.tests.helloTest.test11(helloTest.java:34)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test11 -->
  <testcase name="test11" time="0.056" classname="com.pack.tests.helloTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.pack.common.TestListener.takeScreenShot(TestListener.java:52)
	at com.pack.common.TestListener.onTestFailure(TestListener.java:41)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test11 -->
</testsuite> <!-- Test -->
